sign-commit = false
sign-tag = false
push = true
publish = true
tag-prefix = "v"
allow-branch = ["main"]
dev-version = true

[changelog]
update = false

[commit]
message = "release(fslint): v{{version}}"

