name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install system deps
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libgexiv2-dev pkg-config

      - name: set up git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: install cargo-release
        run: cargo install cargo-release --locked

      - name: run cargo release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
        run: cargo release patch --no-confirm --execute
